--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LuthMC/SimpleWelcome
build-by-default: true
branches:
- stable
projects:
  SimpleWelcomeMessages:
    path: ""
    icon: icon.png
...
