name: SimpleWelcome
main: Luthfi\SimpleWelcome\Main
version: 1.1.0
api: 5.0.0
author: Luthfi
description: You can customize welcome message and sound.
commands:
  sw:
    description: Open SimpleWelcome settings
    usage: /sw
    permission: simplewelcome.command.sw
permissions:
  simplewelcome.command.sw:
    description: Allows the use of the /sw command
    default: op
