name: SimpleWelcome
main: Luthfi\SimpleWelcome\Main
version: 1.0.0
api: 5.0.0
author: Luthfi
description: You can customize welcome message and sound.
commands:
  sw:
    description: "Set the teleport world and coordinates"
    usage: "/sw setworld"
    permission: simplewelcome.setworld
permissions:
  simplewelcome.setworld:
    default: op
