enabled: true

# SimpleWelcome V1.1.0
# Github: https://github.com/LuthMC
#
# You can see all available tags on wiki!
# https://github.com/LuthMC/SimpleWelcome/wiki/Available-Tags

messages:
  title: "§fWelcome, §b{name}!"
  subtitle: "Example Messages §7| §fTime: {time} WIB"
  auctionbar: "§l{online} Players | Your ping is {ping} ms."
  sound: "note.bell"  # Default sound

join_leave:
  enabled: true
  join_message: "{name} has joined the game"
  leave_message: "{name} has left the game"

teleport:
  enabled: true
  world: "world"
  x: 0
  y: 100
  z: 0
  
time:
  timezone: "Asia/Jakarta" # NOTE: use this https://php.net/manual/en/timezones.php
