enabled: true

# add tags and auctionbar! you can use {name} and {ping} tags now!
messages:
  title: "§fWelcome, §b{name}!"
  subtitle: "§l§bExample Messages"
  auctionbar: "Welcome {name}! Your ping is {ping} ms."
  sound: "note.bell"  # Default sound

join_leave:
  enabled: true
  join_message: "{name} has joined the game"
  leave_message: "{name} has left the game"
