enabled: true

# SimpleWelcome V1.1.0
# Github: https://github.com/LuthMC
#
# Available Tags
# {name} = players names.
# {world_name} = world name.
# {ping} = show their ping.
# {x} {y} {z} = show their coordinates.
# {online} = show how many player in servers.
# {date} = show date.
# {time} = show time.
# {ip} {port} = will show ip and port servers.

messages:
  title: "§fWelcome, §b{name}!"
  subtitle: "Example Messages §7| §fTime: {time} WIB"
  auctionbar: "§l{online} Players | Your ping is {ping} ms."
  sound: "note.bell"  # Default sound

join_leave:
  enabled: true
  join_message: "{name} has joined the game"
  leave_message: "{name} has left the game"

teleport:
  enabled: true
  world: "world"
  x: 0
  y: 100
  z: 0
  
time:
  timezone: "Asia/Jakarta" # NOTE: use this https://php.net/manual/en/timezones.php
